// Node connections for navigation graph
// Each node maps to an array of neighboring nodes it connects to

export const nodeConnections = {
  defaultStartNode: ['pointA', 'newPointD'],
  pointA: ['defaultStartNode', 'pointB', 'newPointAE', 'newPointFm'],
  newPointJg: ['newPointJf', 'newPointHq', 'newPointHs'],
  pointB: ['pointA', 'pointC', 'pointN', 'pointM'],
  pointC: ['pointB', 'pointD', 'pointK'],
  pointD: ['pointC', 'pointE'],
  pointE: ['pointD', 'pointF', 'pointK'],
  pointF: ['pointE', 'pointG', 'pointH'],
  pointG: ['pointF'],
  pointH: ['pointF', 'pointK', 'pointL'],
  pointK: ['pointH', 'pointE', 'pointC'],
  pointL: ['pointH', 'pointM', 'pointP'],
  pointM: ['pointL', 'pointO', 'pointB'],
  pointN: ['pointB', 'pointO', 'newPointD', 'newPointK'],
  newPointK: ['newPointF', 'newPointC', 'pointN', 'pointQ'],
  pointO: ['pointN', 'pointP', 'pointQ', 'pointM'],
  pointP: ['pointO', 'pointL', 'pointT', 'newPointL'],
  newPointL: ['newPointO1', 'newPointM', 'pointP'],
  newPointO1: ['newPointL', 'newPointO'],
  newPointO: ['newPointO1', 'newPointM'],
  newPointM: ['newPointO', 'newPointL', 'newPointN'],
  newPointN: ['newPointM'],
  pointQ: ['pointO', 'pointR', 'newPointK', 'newPointG'],
  newPointG: ['newPointH1', 'newPointF', 'pointQ'],
  newPointF: ['newPointG', 'newPointE', 'newPointK'],
  newPointE: ['newPointF', 'newPointR', 'newPointE1'],
  newPointE1: ['newPointE', 'newPointE2'],
  newPointE2: ['newPointE1', 'newPointE3'],
  newPointE3: ['newPointE2', 'newPointE4'],
  newPointE4: ['newPointE3', 'newPointE5'],
  newPointE5: ['newPointE4', 'newPointE6'],
  newPointE6: ['newPointE5', 'newPointE7'],
  newPointE7: ['newPointE6', 'newPointE8'],
  newPointE8: ['newPointE7', 'newPointE9'],
  newPointE9: ['newPointE8', 'newPointAK'],
  newPointR: ['newPointE', 'newPointQ'],
  newPointQ: ['newPointR', 'newPointC', 'newPointT'],
  newPointC: ['newPointQ', 'newPointP', 'newPointV','newPointK'],
  newPointV: ['newPointC', 'newPointD', 'newPointW1'],
  newPointW: ['newPointW1', 'newPointP', 'newPointAA2'],
  newPointH1: ['newPointG', 'newPointH', 'newPointJ'],
  newPointJ: ['newPointH1', 'newPointI', 'pointR'],
  newPointH: ['newPointI', 'newPointH1'],
  newPointI: ['newPointH', 'newPointJ', 'pointS'],
  pointR: ['pointQ', 'pointT', 'newPointJ'],
  pointS: ['pointU', 'pointT', 'newPointI'],
  pointT: ['pointS', 'pointR', 'pointP'],
  pointU: ['pointS', 'pointV', 'pointad'],
  pointV: ['pointU', 'pointW', 'pointac'],
  pointW: ['pointV', 'pointX', 'pointaa'],
  pointX: ['pointW', 'pointY'],
  pointY: ['pointX', 'pointZ'],
  pointZ: ['pointY', 'pointaa'],
  pointaa: ['pointZ', 'pointab', 'pointW'],
  pointab: ['pointaa', 'pointac'],
  pointac: ['pointab', 'pointad', 'pointV'],
  pointad: ['pointac', 'pointU'],
  extPointCtop4: ['extPointCtop3'],
  extPointCtop3: ['extPointCtop2', 'extPointCtop4'],
  extPointCtop2: ['extPointCtop1', 'extPointCtop3'],
  extPointCtop1: ['extPointC', 'extPointCtop2'],
  extPointC: ['extPointD', 'extPointB', 'extPointCtop1'],
  extPointB: ['extPointA', 'extPointC'],
  extPointA: ['extPointB'],
  extPointD: ['extPointC', 'extPointE', 'extPointDleft1'],
  extPointDleft1: ['extPointD'],
  extPointF: ['extPointD', 'extPointG'],
  extPointG: ['extPointF', 'extPointH'],
  extPointH: ['extPointG', 'extPointI', 'extPointHtop1'],
  extPointHtop1: ['extPointH'],
  extPointI: ['extPointH', 'extPointJ'],
  extPointJ: ['extPointI', 'extPointK'],
  extPointK: ['extPointJ', 'extPointL'],
  extPointL: ['extPointK', 'extPointM'],
  extPointM: ['extPointL', 'extPointN'],
  extPointN: ['extPointM', 'extPointO', 'extPointNleft1'],
  extPointNleft1: ['extPointN', 'extPointNleft2', 'newPointFe'],
  newPointFe: ['extPointNleft1'],
  extPointNleft2: ['extPointNleft1', 'extPointS', 'extPointNleft3'],
  extPointNleft3: ['extPointNleft2', 'extPointNleft4'],
  extPointNleft4: ['extPointNleft3', 'extPointNleft5'],
  extPointNleft5: ['extPointNleft4', 'extPointNleft6'],
  extPointNleft6: ['extPointNleft5', 'extPointNleft8'],
  extPointNleft7: ['extPointNleft8', 'extPointNleft9'],
  extPointNleft8: ['extPointNleft7', 'extPointNleft6'],
  extPointNleft9: ['extPointNleft7', 'extPointNleft10'],
  extPointNleft10: ['extPointNleft9', 'extPointNleft11'],
  extPointNleft11: ['extPointNleft10', 'extPointNleft12'],
  extPointNleft12: ['extPointNleft11', 'extPointNleft13'],
  extPointNleft13: ['extPointNleft12', 'extPointNleft14'],
  extPointNleft14: ['extPointNleft13', 'newPointFh'],
  newPointFh: ['extPointNleft14'],

  extPointO: ['extPointN', 'extPointP'],
  extPointP: ['extPointO', 'extPointQ'],
  extPointQ: ['extPointP', 'extPointR'],
  extPointR: ['extPointQ', 'extPointS'],
  extPointS: ['extPointR', 'extPointT', 'extPointNleft2'],
  extPointT: ['extPointS', 'extPointU', 'newPointFa'],
  newPointFa: ['extPointT'],
  extPointU: ['extPointT', 'extPointV'],
  extPointV: ['extPointU', 'extPointW', 'newPointEy'],
  newPointEy: ['extPointV'],
  extPointW: ['extPointV', 'extPointX', 'newPointDp'],
  newPointDp: ['extPointW'],
  extPointX: ['extPointW', 'extPointY', 'newPointDq'],
  newPointDq: ['extPointX', 'newPointDr'],
  newPointDr: ['newPointDq', 'newPointDs', 'newPointDw', 'newPointDu'],
  newPointDw: ['newPointDr', 'newPointDv'],
  newPointDv: ['newPointDw', 'newPointDu', 'newPointEe'],
  newPointEe: ['newPointDv'],
  newPointDu: ['newPointDr', 'newPointDv', 'newPointEb', 'newPointDt'],
  newPointDs: ['newPointDr', 'newPointDt'],
  newPointDt: ['newPointDu', 'newPointDs', 'newPointDx'],
  newPointDx: ['newPointDt', 'newPointEb', 'newPointDy'],
  newPointDy: ['newPointDx', 'newPointDz', 'newPointEa'],
  newPointEa: ['newPointDy', 'newPointEa1'],
  newPointEa1: ['newPointEa', 'newPointEw', 'newPointEo'],
  newPointEw: ['newPointEa1', 'newPointEu'],
  newPointEu: ['newPointEw', 'newPointEv1', 'newPointEt'],
  newPointEv1: ['newPointEu', 'newPointEv'],
  newPointEv: ['newPointEv1'],
  newPointEt: ['newPointEu', 'newPointEp', 'newPointEs'],
  newPointEs: ['newPointEt', 'newPointEr'],
  newPointEr: ['newPointEs', 'newPointEp'],
  newPointEp: ['newPointEt', 'newPointEo', 'newPointEr'],
  newPointEo: ['newPointEp', 'newPointEa1', 'newPointEn1'],
  newPointEn1: ['newPointEo', 'newPointEn'],
  newPointEn: ['newPointEn1', 'newPointDz', 'newPointEm'],
  newPointDz: ['newPointEn', 'newPointDy', 'newPointEd'],
  newPointEd: ['newPointDz', 'newPointEc', 'newPointEm'],
  newPointEm: ['newPointEd', 'newPointEn', 'newPointEl'],
  newPointEb: ['newPointDu', 'newPointDx', 'newPointEc'],
  newPointEc: ['newPointEb', 'newPointEd', 'newPointEg'],
  newPointEg: ['newPointEc', 'newPointEg1', 'newPointEh'],
  newPointEg1: ['newPointEg', 'newPointEg2'],
  newPointEg2: ['newPointEg1', 'newPointEf'],
  newPointEf: ['newPointEg2'],
  newPointEh: ['newPointEg', 'newPointEh1', 'newPointEl'],
  newPointEh1: ['newPointEh', 'newPointEi'],
  newPointEi: ['newPointEh1', 'newPointEj', 'newPointEl'],
  newPointEj: ['newPointEi', 'newPointEj1'],
  newPointEj1: ['newPointEj', 'newPointEk'],
  newPointEk: ['newPointEj1'],
  newPointEl: ['newPointEh', 'newPointEi', 'newPointEm'],

  extPointY: ['extPointX', 'extPointaa', 'newPointDn'],
  newPointDn: ['extPointY'],
  extPointaa: ['extPointY', 'newPointDa', 'newPointDe'],
  newPointD: ['defaultStartNode', 'pointN', 'newPointV'],
  newPointAE: ['pointA'],
  newPointT: ['newPointQ', 'newPointU', 'newPointS'],
  newPointU: ['newPointT', 'newPointAB1'],
  newPointAB: ['newPointAB2', 'newPointAA', 'newPointAB1'],
  newPointAA: ['newPointAB', 'newPointAA2', 'newPointAA1'],
  newPointZ: ['newPointAB2', 'newPointZ2', 'newPointAC'],
  newPointAC: ['newPointZ', 'newPointAD', 'newPointY'],
  newPointAD: ['newPointAC'],
  newPointY: ['newPointAC', 'newPointX'],
  newPointX: ['newPointY', 'newPointAE'],
  newPointAE: ['newPointX', 'pointA'],
  newPointZ1: ['newPointW1', 'newPointZ2', 'newPointX'],
  newPointZ2: ['newPointZ1', 'newPointZ'],
  newPointW1: ['newPointZ1', 'newPointW', 'newPointV'],
  newPointAB2: ['newPointZ', 'newPointAB'],
  newPointAB1: ['newPointAB', 'newPointU'],
  newPointAA2: ['newPointAA', 'newPointW'],
  newPointAA1: ['newPointAA', 'newPointS'],
  newPointS: ['newPointAA1', 'newPointT', 'newPointP'],
  newPointP: ['newPointS', 'newPointC', 'newPointW'],
  newPointAK: ['newPointAJ', 'newPointAH', 'newPointE9'],
  newPointAJ: ['newPointAK', 'newPointBC', 'newPointBB'],
  newPointBC: ['newPointAJ', 'newPointBA', 'newPointAL1'],
  newPointAL1: ['newPointBC', 'newPointAL', 'newPointAZ1'],
  newPointAL: ['newPointAL1', 'newPointAI', 'newPointAM1'],
  newPointAI: ['newPointAL'],
  newPointAM1: ['newPointAL', 'newPointAM', 'newPointAU'],
  newPointAM: ['newPointAM1', 'newPointAV'],
  newPointAH: ['newPointAK', 'newPointBB', 'newPointAS1'],
  newPointBB: ['newPointAH', 'newPointAJ', 'newPointBA', 'newPointAS'],
  newPointBA: ['newPointBB', 'newPointAT', 'newPointAZ', 'newPointBC'],
  newPointAZ: ['newPointBA', 'newPointAZ1', 'newPointAN'],
  newPointAZ1: ['newPointAZ', 'newPointAL1', 'newPointAU'],
  newPointAU: ['newPointAZ1', 'newPointAM1', 'newPointAV', 'newPointAO'],
  newPointAV: ['newPointAU', 'newPointAP', 'newPointAM', 'newPointAW'],
  newPointAW: ['newPointAV', 'newPointAY', 'newPointAX', 'newPointAQ'],
  newPointAX: ['newPointAW', 'newPointAR'],
  newPointAY: ['newPointAW'],
  newPointAS1: ['newPointAH', 'newPointAS', 'newPointAG'],
  newPointAS: ['newPointAS1', 'newPointAT', 'newPointBB', 'newPointBD'],
  newPointAT: ['newPointAS', 'newPointAN', 'newPointBA'],
  newPointAN: ['newPointAT', 'newPointAZ', 'newPointAO', 'newPointBG'],
  newPointAO: ['newPointAN', 'newPointBH', 'newPointAU', 'newPointAP'],
  newPointAP: ['newPointAO', 'newPointAV', 'newPointAQ', 'newPointBI'],
  newPointAQ: ['newPointAP', 'newPointAW', 'newPointAR', 'newPointBQ'],
  newPointAR: ['newPointAQ', 'newPointAX', 'newPointAR1'],
  newPointAR1: ['newPointAR'],
  newPointBQ: ['newPointBP', 'newPointBR', 'newPointAQ'],
  newPointBP: ['newPointBQ'],
  newPointBR: ['newPointBQ', 'newPointBS', 'newPointBU'],
  newPointBU: ['newPointBR'],
  newPointBS: ['newPointBR', 'newPointBT', 'newPointBV'],
  newPointBV: ['newPointBS', 'newPointBW'],
  newPointBT: ['newPointBS', 'newPointBK', 'newPointBW'],
  newPointBW: ['newPointBT', 'newPointBX', 'newPointBV'],
  newPointBX: ['newPointBW', 'newPointBM'],
  newPointBM: ['newPointBX', 'newPointBL', 'newPointBN1'],
  newPointBN1: ['newPointBM', 'newPointBN', 'newPointBO'],
  newPointBN: ['newPointBN1'],
  newPointBO: ['newPointBN1'],
  newPointBL: ['newPointBM', 'newPointBY', 'newPointBK'],
  newPointBK: ['newPointBL', 'newPointBT', 'newPointBJ'],
  newPointBJ: ['newPointBK', 'newPointBI', 'newPointBZ'],
  newPointBI: ['newPointBJ', 'newPointBH', 'newPointAP'],
  newPointBH: ['newPointBI', 'newPointAO', 'newPointBG'],
  newPointBG: ['newPointBH', 'newPointAN', 'newPointBF', 'newPointCH'],
  newPointCH: ['newPointBG'],
  newPointBF: ['newPointBG', 'newPointCI', 'newPointBD'],
  newPointBD: ['newPointBF', 'newPointCJ', 'newPointBE', 'newPointAS'],
  newPointBE: ['newPointAG', 'newPointBD', 'newPointCX'],
  newPointAG: ['newPointAS1', 'newPointBE', 'newPointAF'],
  newPointAF: ['newPointAG'],
  newPointCX: ['newPointBE', 'newPointCK', 'newPointCW'],
  newPointCW: ['newPointCX', 'newPointCV', 'newPointCU'],
  newPointCV: ['newPointCW'],
  newPointCU: ['newPointCW'],
  newPointCK: ['newPointCX', 'newPointCN', 'newPointCJ'],
  newPointCJ: ['newPointCK', 'newPointCI', 'newPointBD'],
  newPointCI: ['newPointCJ', 'newPointBF', 'newPointCM'],
  newPointCM: ['newPointCI', 'newPointCS', 'newPointCL'],
  newPointCL: ['newPointCM', 'newPointCN', 'newPointCO'],
  newPointCN: ['newPointCL', 'newPointCK', 'newPointCT'],
  newPointCT: ['newPointCN', 'newPointCO', 'newPointCY'],
  newPointCO: ['newPointCP', 'newPointCL', 'newPointCT'],
  newPointCP: ['newPointCO', 'newPointCQ', 'newPointCS'],
  newPointCQ: ['newPointCP', 'newPointCR'],
  newPointCR: ['newPointCQ', 'newPointCS'],
  newPointCS: ['newPointCR', 'newPointCP', 'newPointCM'],
  newPointBY: ['newPointBL', 'newPointBZ'],
  newPointBZ: ['newPointBY', 'newPointBJ', 'newPointCA'],
  newPointCA: ['newPointBZ', 'newPointCB', 'newPointCE'],
  newPointCE: ['newPointCA'],
  newPointCB: ['newPointCA', 'newPointCC', 'newPointCF'],
  newPointCF: ['newPointCB'],
  newPointCC: ['newPointCB', 'newPointCD', 'newPointCC1'],
  newPointCC1: ['newPointCC', 'newPointCG'],
  newPointCG: ['newPointCC1'],
  newPointCD: ['newPointCC'],
  newPointCY: ['newPointCT', 'newPointCZ1', 'newPointDa'],
  newPointCZ1: ['newPointCY', 'newPointCZ'],
  newPointCZ: ['newPointCZ1'],
  newPointDa: ['newPointCY', 'extPointaa', 'newPointDc1'],
  newPointDc1: ['newPointDa', 'newPointDb', 'newPointDc'],
  newPointDb: ['newPointDc1'],
  newPointDc: ['newPointDc1'],
  newPointDe: ['extPointaa', 'newPointDf', 'newPointDe1'],
  newPointDe1: ['newPointDe', 'newPointDe2'],
  newPointDe2: ['newPointDe1', 'newPointDl'],
  newPointDl: ['newPointDe2'],
  newPointDf: ['newPointDe', 'newPointDg', 'newPointDh'],
  newPointDg: ['newPointDf'],
  newPointDh: ['newPointDf', 'newPointDi', 'newPointDk'],
  newPointDk: ['newPointDh'],
  newPointDi: ['newPointDh', 'newPointDj'],
  newPointDj: ['newPointDi'],
  newPointFm: ['pointA', 'newPointFo', 'newPointFr'],
  newPointFo: ['newPointFm', 'newPointFp'],
  newPointFp: ['newPointFo', 'newPointFq'],
  newPointFq: ['newPointFp'],
  newPointFr: ['newPointFm', 'newPointFs'],
  newPointFs: ['newPointFr', 'newPointFt', 'newPointGg'],
  newPointFt: ['newPointFs', 'newPointFu'],
  newPointFu: ['newPointFt', 'newPointFv'],
  newPointFv: ['newPointFu', 'newPointFw'],
  newPointFw: ['newPointFv', 'newPointFx'],
  newPointFx: ['newPointFw', 'newPointFy'],
  newPointFy: ['newPointFx', 'newPointFz'],
  newPointFz: ['newPointFy', 'newPointGa'],
  newPointGa: ['newPointFz', 'newPointGb'],
  newPointGb: ['newPointGa', 'newPointGc'],
  newPointGc: ['newPointGb', 'newPointGd'],
  newPointGd: ['newPointGc', 'newPointGe'],
  newPointGe: ['newPointGd', 'newPointGf'],
  newPointGf: ['newPointGe'],
  newPointGg: ['newPointFs', 'newPointGh'],
  newPointGh: ['newPointGg', 'newPointGi', 'newPointGj'],
  newPointGi: ['newPointGh'],
  newPointGj: ['newPointGh', 'newPointGk', 'newPointGo'],
  newPointGk: ['newPointGj', 'newPointGl'],
  newPointGl: ['newPointGk', 'newPointGm'],
  newPointGm: ['newPointGl', 'newPointGn'],
  newPointGn: ['newPointGm'],
  newPointGo: ['newPointGj', 'newPointGp'],
  newPointGp: ['newPointGo', 'newPointGq'],
  newPointGq: ['newPointGp', 'newPointGr', 'newPointHo'],
  newPointGr: ['newPointGq', 'newPointGs'],
  newPointGs: ['newPointGr', 'newPointGt'],
  newPointGt: ['newPointGs', 'newPointGu', 'newPointGz'],
  newPointGu: ['newPointGt', 'newPointGv'],
  newPointGv: ['newPointGu', 'newPointGw'],
  newPointGw: ['newPointGv', 'newPointGx'],
  newPointGx: ['newPointGw', 'newPointGy'],
  newPointGy: ['newPointGx', 'newPointGz', 'newPointHi'],
  newPointGz: ['newPointGy', 'newPointHa', 'newPointGt'],
  newPointHa: ['newPointGz', 'newPointHb', 'newPointHg'],
  newPointHb: ['newPointHa', 'newPointHc'],
  newPointHc: ['newPointHb', 'newPointHd'],
  newPointHd: ['newPointHc', 'newPointHe'],
  newPointHe: ['newPointHd', 'newPointHf'],
  newPointHf: ['newPointHe', 'newPointHg'],
  newPointHg: ['newPointHf', 'newPointHa'],
  newPointHi: ['newPointGy', 'newPointHn', 'newPointHj'],
  newPointHj: ['newPointHi', 'newPointHk', 'newPointHl', 'newPointHm'],
  newPointHk: ['newPointHj'],
  newPointHl: ['newPointHj'],
  newPointHm: ['newPointHj'],
  newPointHn: ['newPointHi'],
  newPointHo: ['newPointGq', 'newPointHp'],
  newPointHp: ['newPointHo', 'newPointHq'],
  newPointHq: ['newPointHp', 'newPointHr', 'newPointJg'],
  newPointHr: ['newPointHq', 'newPointHs'],
  newPointHs: ['newPointHr', 'newPointHt', 'newPointJg'],
  newPointHt: ['newPointHs', 'newPointHu', 'newPointJf'],
  newPointHu: ['newPointHt', 'newPointHv', 'newPointJe'],
  newPointHv: ['newPointHu', 'newPointHw', 'newPointJd', 'newPointIz'],
  newPointHw: ['newPointHv', 'newPointHx'],
  newPointHx: ['newPointHw', 'newPointHy', 'newPointIz'],
  newPointHy: ['newPointHx', 'newPointIy', 'newPointHz'],
  newPointHz: ['newPointHy', 'newPointIu', 'newPointIa'],
  newPointIa: ['newPointHz', 'newPointId', 'newPointIb'],
  newPointIb: ['newPointIa', 'newPointIc'],
  newPointIc: ['newPointIb', 'newPointId', 'newPointIf'],
  newPointId: ['newPointIc', 'newPointIa', 'newPointIe'],
  newPointIe: ['newPointId', 'newPointIf', 'newPointIo'],
  newPointIf: ['newPointIe', 'newPointIc', 'newPointIg'],
  newPointIg: ['newPointIf', 'newPointIh'],
  newPointIh: ['newPointIg', 'newPointIi', 'newPointIl'],
  newPointIi: ['newPointIh', 'newPointIj', 'newPointIk'],
  newPointIj: ['newPointIi'],
  newPointIk: ['newPointIi', 'newPointIl', 'newPointIp'],
  newPointIl: ['newPointIk', 'newPointIh', 'newPointIm'],
  newPointIm: ['newPointIl', 'newPointIn', 'newPointIp'],
  newPointIn: ['newPointIm', 'newPointIo', 'newPointIr'],
  newPointIo: ['newPointIn', 'newPointIt', 'newPointIe'],
  newPointIp: ['newPointIk', 'newPointIm', 'newPointIq'],
  newPointIq: ['newPointIp', 'newPointIr'],
  newPointIr: ['newPointIq', 'newPointIs', 'newPointIn'],
  newPointIs: ['newPointIr', 'newPointIt', 'newPointIv', 'newPointJc'],
  newPointIt: ['newPointIs', 'newPointIu', 'newPointIo'],
  newPointIu: ['newPointIt', 'newPointHz', 'newPointIy', 'newPointIv'],
  newPointIv: ['newPointIu', 'newPointIs', 'newPointIw'],
  newPointIw: ['newPointIv', 'newPointIx', 'newPointIy'],
  newPointIx: ['newPointIw', 'newPointJa', 'newPointIz'],
  newPointIz: ['newPointIx', 'newPointIy', 'newPointHv', 'newPointHx'],
  newPointJa: ['newPointIx', 'newPointJb', 'newPointJd'],
  newPointJb: ['newPointJa', 'newPointJc'],
  newPointJc: ['newPointJb', 'newPointIs'],
  newPointJd: ['newPointJa', 'newPointJe', 'newPointHv'],
  newPointJe: ['newPointJd', 'newPointJf', 'newPointHu'],
  newPointJf: ['newPointJe', 'newPointJg', 'newPointHt'],
};

export default nodeConnections;
